import os
import re
import json
import smtplib
from email.message import EmailMessage
from email.utils  import formatdate, make_msgid
from datetime     import date
from dotenv       import load_dotenv

load_dotenv()

# Each user's config lives in their own USER_DIR set by the parent process.
_USER_DIR = os.environ.get("USER_DIR", os.path.dirname(os.path.abspath(__file__)))


# ── HTML email builder ────────────────────────────────────────────────────────

def _build_html(name, content, num_matches):
    """
    Convert the plain-text results block into a clean HTML email.
    Having an HTML alternative dramatically reduces spam-filter scores.
    """
    today = date.today().strftime("%B %d, %Y")

    # Split on the 50-dash dividers that main.py writes between jobs
    blocks = re.split(r'-{30,}', content)

    cards_html = ""
    for block in blocks:
        block = block.strip()
        if not block:
            continue

        score_m  = re.search(r'Match Score\s*:\s*(\d+)%', block)
        title_m  = re.search(r'^(.+?)\s*[—\-]\s*(.+)$', block, re.MULTILINE)
        loc_m    = re.search(r'Location\s*:\s*(.+)',    block)
        date_m   = re.search(r'Posted On\s*:\s*(.+)',   block)
        url_m    = re.search(r'Apply\s*:\s*(https?://\S+)', block)
        reason_m = re.search(r'Reason:\s*(.+)',         block)

        if not score_m:
            continue   # skip non-job blocks

        score   = score_m.group(1)
        title   = title_m.group(1).strip()   if title_m   else "Position"
        company = title_m.group(2).strip()   if title_m   else "Company"
        loc     = loc_m.group(1).strip()     if loc_m     else ""
        posted  = date_m.group(1).strip()    if date_m    else ""
        url     = url_m.group(1).strip()     if url_m     else "#"
        reason  = reason_m.group(1).strip()  if reason_m  else ""

        score_int  = int(score) if score.isdigit() else 0
        badge_col  = "#27ae60" if score_int >= 85 else "#e67e22" if score_int >= 75 else "#2980b9"

        loc_row    = f'<p style="margin:4px 0;font-size:.85rem;color:#6b7d8e;">📍 {loc}</p>'    if loc    else ""
        date_row   = f'<p style="margin:4px 0;font-size:.85rem;color:#6b7d8e;">📅 Posted: {posted}</p>' if posted else ""
        reason_row = f'<p style="margin:10px 0 0;font-size:.84rem;color:#444;line-height:1.55;">{reason}</p>' if reason else ""

        cards_html += f"""
<div style="border:1px solid #dde6f0;border-radius:10px;padding:20px;margin-bottom:14px;background:#fff;">
  <div style="display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:10px;">
    <div>
      <h3 style="margin:0;font-size:1rem;color:#1c2b3a;">{title}</h3>
      <p  style="margin:3px 0 0;font-size:.87rem;color:#6b7d8e;">{company}</p>
    </div>
    <span style="background:{badge_col};color:#fff;padding:3px 12px;border-radius:20px;
                 font-size:.82rem;font-weight:700;white-space:nowrap;flex-shrink:0;margin-left:12px;">
      {score}% match
    </span>
  </div>
  {loc_row}{date_row}{reason_row}
  <a href="{url}" style="display:inline-block;margin-top:14px;padding:8px 20px;
                         background:#1f618d;color:#fff;text-decoration:none;
                         border-radius:8px;font-size:.84rem;font-weight:600;">
    Apply Now →
  </a>
</div>"""

    greeting = f"Hi {name}," if name else "Hi,"

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>JobMatchAI Results</title>
</head>
<body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Arial,sans-serif;
             background:#f4f6f9;margin:0;padding:0;">
<div style="max-width:640px;margin:0 auto;padding:24px 16px;">

  <!-- Header -->
  <div style="background:linear-gradient(135deg,#1f618d,#2980b9);border-radius:12px;
              padding:30px 28px;margin-bottom:20px;text-align:center;">
    <h1 style="color:#fff;margin:0 0 6px;font-size:1.55rem;font-weight:800;">
      JobMatchAI — Daily Results
    </h1>
    <p style="color:rgba(255,255,255,.82);margin:0;font-size:.93rem;">{today}</p>
  </div>

  <!-- Intro -->
  <div style="background:#fff;border-radius:10px;padding:18px 22px;
              margin-bottom:18px;border:1px solid #dde6f0;">
    <p style="margin:0;font-size:.95rem;color:#1c2b3a;line-height:1.6;">
      {greeting}<br><br>
      Your pipeline found <strong>{num_matches} high-quality job
      match{'es' if num_matches != 1 else ''}</strong> today.
      A tailored resume and cover letter PDF is attached for each match below.
    </p>
  </div>

  <!-- Job cards -->
  {cards_html}

  <!-- Footer -->
  <p style="text-align:center;font-size:.72rem;color:#aaa;margin-top:22px;line-height:1.6;">
    Generated by JobMatchAI &middot; {today}<br>
    {num_matches * 2} PDF attachments — tailored resume + cover letter per match
  </p>

</div>
</body>
</html>"""


# ── Resend sender (HTTPS — works on Render and all cloud hosts) ───────────────

def _send_via_resend(receiver, name, subject, text_body, html_body,
                     attachments, api_key):
    """
    Send via the Resend API (HTTPS on port 443).

    Render free tier blocks all outbound SMTP ports (25 / 465 / 587).
    Resend communicates over HTTPS so it is never blocked.

    Free plan: 3 000 emails / month — plenty for a daily job pipeline.
    Sign-up: https://resend.com  (< 1 minute, no credit card)
    """
    import resend  # pip install resend

    resend.api_key = api_key

    # Build attachment list — Resend expects bytes
    att_list = []
    for fp in attachments:
        try:
            with open(fp, "rb") as f:
                data = f.read()
            att_list.append({
                "filename": os.path.basename(fp),
                "content":  list(data),   # SDK accepts list[int] bytes
            })
        except Exception as e:
            print(f"  Attachment skipped ({os.path.basename(fp)}): {e}")

    params: resend.Emails.SendParams = {
        "from":        "JobMatchAI <onboarding@resend.dev>",
        "to":          [receiver],
        "reply_to":    receiver,
        "subject":     subject,
        "text":        text_body,
        "html":        html_body,
        "attachments": att_list,
    }

    resend.Emails.send(params)
    print(f"  Email sent via Resend → {receiver}")


# ── SMTP sender (for local development) ──────────────────────────────────────

def _send_via_smtp(sender, password, receiver, name, subject,
                   text_body, html_body, attachments):
    """
    Send via Gmail SMTP SSL (port 465).

    Works perfectly for local development.
    NOT suitable for Render/cloud hosts that block outbound SMTP.
    Set RESEND_API_KEY in Render env vars to use Resend instead.
    """
    msg = EmailMessage()
    msg["From"]       = f"{name} <{sender}>" if name else sender
    msg["To"]         = receiver
    msg["Subject"]    = subject
    msg["Date"]       = formatdate(localtime=True)
    msg["Message-ID"] = make_msgid(
        domain=sender.split("@")[-1] if "@" in (sender or "") else "jobmatchai.local"
    )

    msg.set_content(text_body)
    try:
        msg.add_alternative(html_body, subtype="html")
    except Exception as e:
        print(f"  HTML body skipped: {e}")

    for file_path in attachments:
        try:
            with open(file_path, "rb") as f:
                data = f.read()
            msg.add_attachment(
                data, maintype="application", subtype="pdf",
                filename=os.path.basename(file_path),
            )
        except Exception as e:
            print(f"  Attachment skipped ({os.path.basename(file_path)}): {e}")

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(sender, password)
        server.send_message(msg)
    print(f"  Email sent via SMTP → {receiver}")


# ── Main entry point ──────────────────────────────────────────────────────────

def send_email(content, attachments):
    sender      = os.getenv("EMAIL",           "")
    password    = os.getenv("EMAIL_PASSWORD",  "")
    resend_key  = os.getenv("RESEND_API_KEY",  "")

    # Pull receiver and sender's name from the user's config file.
    try:
        with open(os.path.join(_USER_DIR, "config.json"), "r", encoding="utf-8") as f:
            _cfg = json.load(f)
        receiver = _cfg.get("receiver_email", "").strip() or _cfg.get("email", "").strip() or sender
        name     = _cfg.get("name", "").strip()
    except Exception:
        receiver = sender
        name     = ""

    today       = date.today().strftime("%B %d, %Y")
    num_matches = max(1, len(attachments) // 2)   # 2 PDFs per job
    subject     = (
        f"Job Match Results — {num_matches} match{'es' if num_matches != 1 else ''}"
        f" · {today}"
    )
    html_body = _build_html(name, content, num_matches)

    # ── Choose transport ──────────────────────────────────────────────────────
    # Render (and most cloud hosts) block outbound SMTP → use Resend.
    # For local dev, fall back to Gmail SMTP if no Resend key is configured.
    if resend_key:
        _send_via_resend(receiver, name, subject, content, html_body,
                         attachments, resend_key)
    else:
        _send_via_smtp(sender, password, receiver, name, subject,
                       content, html_body, attachments)
