services:
  - type: web
    name: matchai-for-everyone
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --threads 4 --timeout 120
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: ADZUNA_APP_ID
        sync: false
      - key: ADZUNA_APP_KEY
        sync: false
      - key: RAPIDAPI_KEY
        sync: false
      - key: USAJOBS_API_KEY
        sync: false
      - key: USAJOBS_EMAIL
        sync: false
      - key: JOOBLE_API_KEY
        sync: false
      - key: FINDWORK_API_KEY
        sync: false
      - key: EMAIL
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: SITE_PASSWORD
        sync: false
